### ISSUE TITLE
otx eval and otx optimize not working

### ISSUE THREAD

**Issue by antaru-ops** [open-edge-platform/training_extensions#2232]
Hi, I have followed exactly with the tutorial for object detection. I am running on Ubuntu 22.04 LTS, Python 3.10, RTX3050, CUDA11.7. I have done exporting the weights.pth model into .xml format with no erros. However, I got this problem when I want to evaluate the openvino model with validation dataset. Here is the screenshot of command and error. 
![image](https://github.com/openvinotoolkit/training_extensions/assets/73929070/3a9a6177-56a0-46ee-89e3-34aa88341adb)

Here is my setting on data.yaml file. This file is located in otx-workspace-DETECTION
![image](https://github.com/openvinotoolkit/training_extensions/assets/73929070/9c0d8006-80db-4565-889f-d48ea5b85d32)

Here is another problem with otx optimize on pre-exported model. I think I have pointed to the correct dataset as mention in the second picture. 
![image](https://github.com/openvinotoolkit/training_extensions/assets/73929070/911d32d6-055f-4094-bc89-c7bcc86a72e8)

Same problem on the openvino model when i do pot
![image](https://github.com/openvinotoolkit/training_extensions/assets/73929070/0f095a15-41e3-457d-a56c-7e106b2c6c28)

**Comment by sungmanc** [comment]
Hi @antaru-ops, Thanks for your reporting. 

Could you try settings like below? Since OTX automatically finds the train / val / test dataset, you just need to input the root directory. 

```
data:
    train:
        ann-files: /home/rtx/Desktop/dru/openvino_sandbox/training_extensions/otx-workspace-DETECTION/splitted_dataset/train/instances_train.json
        data-roots: /home/rtx/Desktop/dru/openvino_sandbox/training_extensions/otx-workspace-DETECTION/splitted_dataset
    val:
        ann-files: /home/rtx/Desktop/dru/openvino_sandbox/training_extensions/otx-workspace-DETECTION/splitted_dataset/val/instances_val.json
        data-roots: /home/rtx/Desktop/dru/openvino_sandbox/training_extensions/otx-workspace-DETECTION/splitted_dataset
```

Or you could use,
```
data:
    train:
        data-roots: /home/rtx/Desktop/dru/openvino_sandbox/training_extensions/otx-workspace-DETECTION/splitted_dataset
    val:
        data-roots: /home/rtx/Desktop/dru/openvino_sandbox/training_extensions/otx-workspace-DETECTION/splitted_dataset
```
